	 ORG 800H  
	 MVI A,0  
	 STA DLUGOSC ; USTAWINIE POCZATKOWEJ DLUGOSCI  
	 LXI H,WYSPODAJ ; TEKST PODANIA LICZBY  
	 RST 3  
	 MVI C,0 ; DLUGOSC WYRAZU  
WPROWADZ  
	 RST 2 ; WPROWADZENIE DANYCH  
	 CPI 0DH ; SPRAEDZENIE CZY UZYTKOWNIK PODAL ENTER  
	 JNZ STOS ; JESLI NIE WPISUJEMY NA STOS  
	 JMP KONWERTUJ ; PRZEJSCIE DO KONWERTOWANIA LICZBY  
STOS  
	 SUI 48D ; ODJECIE Z KODU ASCII  
	 PUSH PSW ; UMIESZCZENIE WARTOSCI NA STOSIE  
	 CALL WALIDACJA ; WALIDACJA ZNAKU  
	 INR C ; INKREMETNACJA LICZNIKA DLUGOSCI LICZBY  
	 MOV A,C  
	 STA DLUGOSC ; PRZECHOWANIE DLUGOSCI  
	 CPI 3 ; SPRAWDZENIE CZY JUZ SA WPROWADZONE 3 ZNAKI  
	 JM WPROWADZ ; JESLI NIE, PRZEJDZ DO KOLEJNEJ ITERACJI  
	 JMP KONWERTUJ ; PRZEJSCIE DO KONWERSJI LICZBY  
WALIDACJA ; SPRAWDZENIE CZY DANY ZNAK JEST LICZBA  
	 STC  
	 CMC ; ZEROWANIE FLAGI CY  
	 CPI 10D ; SPRAWDZENIE CZY WARTOSC MNIEJSZA OD 10  
	 JNC NIELICZBA ; BRAK PRZENIESIENIA, ZNAK NIE JEST LICZBA  
	 RET ; UDANA WALIDACJA, POWROT  
KONWERTUJ  
	 LDA DLUGOSC ; WCZYTANIE ILOSCI ZNAKOW  
	 CPI 0 ; SPRAWDZENIE CZY WYRAZ PUSTY  
	 JZ NIELICZBA ; WYRAZ PUSTY PRZEJDZ DO WYSWIETLENIA BLEDU  
	 POP PSW ; POBIERZ WARTOSC JEDNOSCI Z STOSU  
	 MOV D,A ; ZAPISZ WARTOSC JEDNOSCI W D  
	 LDA DLUGOSC  
	 CPI 1 ; SPRAWDZENIE CZY WYSTEPUJE WARTOSC NA POZYCJI DZIESIATKI  
	 JZ WYSWIETLHEX ; JESLI NIE, PRZEJDZ DO WYSWIETLENIA  
	 POP PSW ; POBIERZ WARTOSC DZIESIATEK Z STOSU  
	 JZ KONIECDEC ; JESLI LICZBA JEST ZEREM, POMIN SUMOWAIE DZIESIATEK  
	 MOV B,A ; USTAWINIE LICZNIKA NA ILOSC DZIESIATEK  
SUMDEC ; SUMOWANIE ILOSCI DZIESIATEK W LICZBIE  
	 MOV A,D ; WCZYTANIE WARTOSCI JEDNOSCI DO AKUMULATORA  
	 ADI 10D ; DODANIE 10  
	 MOV D,A ; SKOPIOWANIE WARTOSCI DO REJESTRU D  
	 DCR B ; DEKREMENTACJA LICZNIKA  
	 MOV A,B ; SKOPIOWANIE WARTOSCI LICZNIKA DO AKUMULATORA  
	 CPI 0D ; SPRAWDZENIE CZY WYSTEPUJE JESZCZE JAKAS DZIESIATKA  
	 JNZ SUMDEC ; JESLI TAK, PRZEJDZ DO DODANIA KOLEJNEJ DZIESIATKI  
KONIECDEC  
	 LDA DLUGOSC ; POBIERZ DLUGOSC Z PAMIECI  
	 CPI 2 ; SPRAWDZ CZY WYSTEPUJA SETKI  
	 JZ WYSWIETLHEX ; JESLI NIE, PRZEJDZ DO WYSWIETLENIA  
	 POP PSW ; POBIERZ WARTOSC SETEK Z STOSU  
	 JZ WYSWIETLHEX ; JESLI ZERO, POMIN ITERACJE DLA SETEK  
	 MOV B,A ; SKOPIUJ ILOSC SETEK DO REJESTRU B A  
SUMHUN  
	 MOV A,D ; SKOPIUJ DO AKUMULATORA WYLICZONA WARTOSC BEZ SETEK  
	 ADI 100D ; DODANIE 10  
	 JC PRZEPELNIENIE ; WALIDACJA, SPRAWDZENIE CZY LICZBA PRZEKRACZA BAJT  
	 MOV D,A ; SKOPIOWANIE WARTOSCI DO REJESTRU D  
	 DCR B ; DEKREMENTACJA LICZNIKA SETEK  
	 MOV A,B  
	 CPI 0D ; SPRAWDZENIE CZY WSYSTEPUJA KOLEJNE SETKI  
	 JNZ SUMHUN ; JESLI TAK, PRZEJDZ DO KOLEJNEJ ITERACJI  
WYSWIETLHEX  
	 LXI H,TEKSTHEX ; WYSWIETLENIE HEX  
	 RST 3  
	 MOV A,D  
	 RST 4 ; WBUDOWANY WYSWIETLACZ WARTOSCI HEX  
	 MVI A,'h'  
	 RST 1  
WYSWIETLBIN  
	 LXI H,TEKSTBIN ; ROZPOCZECIE WYSWIETLANIA BIN  
	 RST 3  
	 MOV A,D ; SKOPIOWANIE LICZBY DO AKUMULATORA  
	 MVI C,8D ; USTAWIENIE LICZNIKA NA 8  
PETLABIN  
	 RAL ; ROTACJA W LEWO. NAJBARDZIEJ ZNACZĄCY BIT TRAFIA DO FLAGI CY  
	 CNC WYSWIETLZERO ; JESLI FLAGA PRZENIESIENIA 0 WYSWIETL 0  
	 CC WYSWIETLJEDEN ; JESLI FLAGA PRZENIESIENIA 1 WYSWIETL 1  
	 DCR C ; DEKREMENTACJA LICZNIKA  
	 JNZ PETLABIN ; JESLI NIE SPRAWDZONO WSZYSTKICH BITOW POWTORZ PETLE  
	 JMP END ; PETLA ZOSTALA WYKONANA 8 RAZY, KONIEC PROGRAMU  
WYSWIETLZERO  
	 MOV B,A ; SKOPIOWANIE LICZBY DO REJESTRU B A  
	 MVI A,'0' ; WPISANIE DO AKUMULATORA KODU ASCII DLA 0  
	 RST 1  
	 MOV A,B ; PRZYWROCENIE WARTOSCI DO AKUMULATORA  
	 RET  
WYSWIETLJEDEN  
	 MOV B,A  
	 MVI A,'1'  
	 RST 1  
	 MOV A,B  
	 RET  
END  
	 HLT  
PRZEPELNIENIE  
	 LXI H,ZADUZA  
	 RST 3  
	 HLT  
NIELICZBA  
	 LXI H,ZLEDANE  
	 RST 3  
	 HLT  
WYSPODAJ  
	 DB 'PODAJ LICZBE:@'                    
TEKSTHEX  
	 DB 10,13,'REPREZENTACJA HEXADECYMALNA:',10,13,'@'                    
TEKSTBIN  
	 DB 10,13,'REPREZENTACJA BINARNA:',10,13,'@'                    
ZLEDANE  
	 DB 10,13,'NIEPOPRAWNE DANE!@'            
ZADUZA  
	 DB 10,13,'ZA DUZA LICZBA!@'    
DLUGOSC 	 DW 920H ; STAŁY ADRES  	 
